name: Playwright Component Tests

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write 

jobs:
  component-visual-regression:
    name: Playwright Component Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-jammy #https://playwright.dev/docs/ci#github-actions-via-containers - keep version in sync with installed package

    steps:
      - uses: actions/checkout@v3

      - run: git config --system --add safe.directory /__w/component-visual-regression-tests/component-visual-regression-tests # to allow updated images changed within a container to be committed, might be ok with --global instead of system

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install Dependencies
        run: pnpm install

      - name: Run Playwright Component tests
        run: pnpm test-update
        env:
          CI: true

      - name: Commit Changed Snapshots
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with: 
          commit_message: "Updated Snapshots"
          # file_pattern: '__component-snapshots__/*' 

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
