name: Playwright Component Tests

on:
  push:
    branches:
      - '**'

jobs:
  component-visual-regression:
    name: Playwright Component Tests
    runs-on: windows-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-jammy #https://playwright.dev/docs/ci#github-actions-via-containers - keep version in sync with installed package

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install Dependencies
        run: pnpm install

      - name: Run Playwright e2e tests
        run: pnpm test
        env:
          CI: true

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
